DROP TABLE IF EXISTS ENROLL;
DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS COURSEDEPT;
DROP TABLE IF EXISTS ADVISOR;
DROP TABLE IF EXISTS STUDENTDEPT;
DROP TABLE IF EXISTS DEPTCHAIR;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS PROFESSOR;

CREATE TABLE IF NOT EXISTS PROFESSOR(
Prof_ID VARCHAR (10) PRIMARY KEY,
Prof_Specialty VARCHAR(15),
Prof_Rank VARCHAR(5),
Prof_LNameNN VARCHAR(15) NOT NULL,
Prof_FNameNN VARCHAR(15) NOT NULL,
Prof_Initial VARCHAR(10),
Prof_Email VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT(
Dept_ID  VARCHAR (10) PRIMARY KEY,
Dept_NameNN VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS COURSE(
Course_ID  VARCHAR (10) PRIMARY KEY,
Course_Title VARCHAR(10) NOT NULL,
Course_Description VARCHAR(20),
Course_Credits DECIMAL (4,2)
);

CREATE TABLE IF NOT EXISTS STUDENT(
Student_ID VARCHAR (10) PRIMARY KEY,
Student_LName VARCHAR(10) NOT NULL,
Student_FName VARCHAR(10) NOT NULL,
Student_Initial VARCHAR(10),
Student_Email VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DEPTCHAIR(
Professor_ID VARCHAR (10),
Dept_ID VARCHAR (10),
CONSTRAINT PK_DEPTCHAIR PRIMARY KEY(Professor_ID, Dept_ID),
CONSTRAINT FK_ProfID FOREIGN KEY (Professor_ID) REFERENCES PROFESSOR(Prof_ID),
CONSTRAINT FK_DeptID FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT(Dept_ID)
);

CREATE TABLE IF NOT EXISTS STUDENTDEPT(
Student_ID VARCHAR (10),
Dept_ID VARCHAR (10),
CONSTRAINT PK_STUDENTDEPT PRIMARY KEY(Student_ID, Dept_ID),
CONSTRAINT FK_StudID FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID),
CONSTRAINT FK_DeptID2 FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT(Dept_ID)
);

CREATE TABLE IF NOT EXISTS ADVISOR(
Professor_ID VARCHAR (10),
Student_ID VARCHAR (10),
CONSTRAINT PK_ADVISOR PRIMARY KEY(Professor_ID, Student_ID),
CONSTRAINT FK_ProfID2 FOREIGN KEY (Professor_ID) REFERENCES PROFESSOR(Prof_ID),
CONSTRAINT FK_StudID2 FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID)
);

CREATE TABLE IF NOT EXISTS COURSEDEPT(
Course_ID VARCHAR (10),
Dept_ID VARCHAR (10),
CONSTRAINT PK_COURSEDEPT PRIMARY KEY(Course_ID, Dept_ID),
CONSTRAINT FK_DeptID3 FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT(Dept_ID)
);

CREATE TABLE IF NOT EXISTS CLASS(
Class_ID VARCHAR (10),
Course_ID VARCHAR (10),
Prof_ID VARCHAR (10),
Class_Section VARCHAR(10),
Class_Days VARCHAR (10),
Class_Time VARCHAR(10),
CONSTRAINT PK_CLASS PRIMARY KEY(Class_ID, Course_ID),
CONSTRAINT FK_CourseID FOREIGN KEY (Course_ID) REFERENCES COURSE(Course_ID)
);

CREATE TABLE IF NOT EXISTS ENROLL(
Student_ID VARCHAR (10),
Course_ID VARCHAR (10),
Class_ID VARCHAR (10),
EnrollmentDateNN date NOT NULL,
GradeNN VARCHAR(4) NOT NULL,
CONSTRAINT PK_ENROLL PRIMARY KEY(Student_ID, Course_ID, Class_ID),
CONSTRAINT FK_StudID3 FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID),
CONSTRAINT FK_CourseID2 FOREIGN KEY (Course_ID) REFERENCES COURSE(Course_ID),
CONSTRAINT FK_ClassID2 FOREIGN KEY (Class_ID) REFERENCES CLASS(Class_ID)
);
